### PR TITLE
fix serializing with nested objects (dictionaries and arrays)

### PR DESCRIPTION
**Pull request by ssuhanov**

### CODE REVIEW

**Comment by ssuhanov** [comment]
I don't know why Travis build failed. All tests passed locally. :(

**Comment by xuyecan** [comment]
In HandyJSON, `Dictionary` extends to conform to the  `_BasicTypeTransformable` protocol, and `_BasicTypeTransformable` derived from `_JSONTransformable`. It means if a value can cast to `Dictionary`, it should also can cast to `_JSONTransformable`. So i think we don't need to modify the code here.

**Comment by ssuhanov** [comment]
@xuyecan yes, you're right. But when you check `as? _JSONTransformable` then you call method from the `extension _JSONTransformable`, not from the `extension Dictionary: _BasicTypeTransformable`. And if you have nested object and this object is `NSDictionary`, it's able to cast as `_JSONTransformable `, but method will call from `extension _JSONTransformable`, not from `extension Dictionary: _BasicTypeTransformable`. And it's sad. :(

**Comment by ssuhanov** [comment]
@xuyecan how are you? What do you think about this issue?

**Comment by ssuhanov** [comment]
@xuyecan The same thing with Array of Dictionaries. I added a couple of rows in the last commit. :)

**Comment by xuyecan** [comment]
Now i finally understand your meaning. `NSDictionary`/`NSArray` isn't conform to any `Transformable` protocol now which make it lost in the serialization/deserialization.

But i think your solution will not fully solve it. Because we should also consider the deserialization which faces the same issue. This [code](https://github.com/alibaba/HandyJSON/blob/74056e15a3dc63aa3a95c48d65b6e2f2d4db0617/HandyJSON/Deserializer.swift#L79) invoke this [code](https://github.com/alibaba/HandyJSON/blob/74056e15a3dc63aa3a95c48d65b6e2f2d4db0617/HandyJSON/Protocol.swift#L139), and `NSDictionary` or `NSArray` type does not hit any of the `if`s. It leads to, nil is returned.

So i think the right way to solve it is to add `_BasicTypeTransformable` extension to `NSDictionary`/`NSArray` like `Dictionary`/`Array`. This way keeps things coherent. What do you think?

But your `case let` style code is amazing to me. I will update all the code fits to it.

**Comment by xuyecan** [comment]
Sorry for too long no reply @ssuhanov . I am too busy recently to follow the issues. Now i am working on them.

**Comment by ssuhanov** [comment]
@xuyecan maybe you should write extensions for NSDictionary and NSArray, but they both always cast to Dictionary and Array. And maybe all what you need to do - cast to Dictionary or Array. Just like I do in my commits. I'm using now this code and everything works fine. :)

**Comment by xuyecan** [comment]
I made a commit [#866d491](https://github.com/alibaba/HandyJSON/commit/866d4919d5af6e81e235fd6b410c50e893324029). You can try this code in your project. If any problem is still there, let me know.

**Comment by ssuhanov** [comment]
@xuyecan it's great. Please tell me when will you renew your framework in the cocoapods?

**Comment by xuyecan** [comment]
Before this weekend. There are still some small features need to develop. I will finish them as soon as possible.

**Comment by ssuhanov** [comment]
@xuyecan thank you. You are great. 👍

**Comment by xuyecan** [comment]
@ssuhanov Thanks. I now close this PR. You can open another one when any new idea come out. Much appreciate.

**Comment by ssuhanov** [comment]
@xuyecan thank you too. I'm so glad to be helpful. :)

**Comment by ssuhanov** [comment]
@xuyecan hi, man. :) Please let me know when you'll update your framework in the cocoapods. Thank you so much. 👍

**Comment by xuyecan** [comment]
I have released 1.7.0 last weekend.
But soon after i found that i forgot to fix an issue where model class inherited from superclass defined in Objective-C 🙈. I just fixed it and release 1.7.1. see: https://cocoapods.org/?q=HandyJSON

**Comment by ssuhanov** [comment]
@xuyecan Everything is great. Thanks for your job. Your framework is awesome and so helpful.

**Pull request closed without merging**
